variable fccAl equal 4.065
variable L1 equal ${fccAl}*54
variable L2 equal ${fccAl}*27
variable Ti equal 1
variable Tf equal 2500

units metal
boundary p p p
atom_style atomic

newton on

region system block -${L1} ${L1} -${L1} ${L1} -${L1} ${L1}
region cube block -${L2} ${L2} -${L2} ${L2} -${L2} ${L2}
create_box 1 system
lattice fcc 4.065
create_atoms 1 region cube # place atoms on lattice
lattice none 1.0 # re-set lattice to default valu

mass            1 26.981539 # Al

# Define potentials
pair_style	    jaxnn cuda12 0.95
pair_coeff	    * * /home/weilong/workspace/chemsim-lammps/examples/aluminium/trainer/output/aluminum_Allegro_r_cutoff_0.5_2025_3_26_parameter/model_default.ptb 1.1 1.1

# Set neighbor communication
neighbor 	    2.0 bin
neigh_modify	delay 0 every 1 check yes

# # Has to be r_cut * (mpl + 1) + skin_dist = 5*(4+1) + 2.5
# For MACE #MLP = 0 ==> 5 * (0 + 1) + 2 = 17 
comm_modify     mode single cutoff 7


velocity all create ${Ti} 425521 rot yes mom yes dist gaussian
fix mynvt all nvt temp ${Ti} ${Tf} 0.1
fix myrc all recenter INIT INIT INIT
timestep 0.001

dump dp1 all atom 10 dump.lammpstrj
thermo 10

run 200