# This LAMMPS input script simulates surface tension measurement of water

variable T equal 293.15 # temperature in Kelvin
variable A2m equal 1e-10 # Angstrom to meter
variable bars2Pa equal 100000 # Atmosphere to Pascal change to bars2Pa
variable N2mN equal 1e3 # Newton to milliNewton

boundary p p p
units metal
atom_style atomic

newton on

pair_style jaxnn cuda12 0.95
pair_modify shift yes mix arithmetic

lattice sc 3.4
region box block -3 3 -3 3 -7 7
create_box 2 box
region fluid block INF INF INF INF -3 3

mass 1 15.9994 # oxygen
mass 2 1.008 # hydrogen


molecule h2omol tip3p.mol
create_atoms 0 region fluid mol h2omol 482793

pair_coeff * * /home/weilong/workspace/chemsim-lammps/examples/bulk_water/output/water_Allegro_r_cutoff_0.6_2025_3_10_emd_128_full_dataset/model_default.ptb 1.1 1.1

neighbor 2.5 bin
neigh_modify every 10 delay 0 check yes

comm_modify mode single cutoff 8.5

# dynamics
velocity all create ${T} 4928459 mom yes rot yes dist gaussian 
fix mynve all nve
fix myber all langevin ${T} ${T} 100. 482793

timestep 0.0005

# output and run
# first : equilibrate the system at temperature T
# thermo 1000
# run 10000

# outputs
variable xPress equal c_thermo_press[1]
variable yPress equal c_thermo_press[2]
variable zPress equal c_thermo_press[3]
variable lz equal lz
variable myst equal 0.5*${lz}*(v_zPress-0.5*(v_xPress+v_yPress))*${A2m}*${bars2Pa}*${N2mN}
dump mydmp all atom 5000 dump.lammpstrj
compute mytemp all temp
fix myat1 all ave/time 10 500 5000 c_mytemp file temperatureVStime.dat
fix myat2 all ave/time 10 500 5000 v_myst file surfacetensionVStime.dat

# longer run for surface tension measurement
run 100000