# LAMMPS input script for solidification of nano-polycrystalline aluminum with separate dump files and temperature logging

# Set variables
variable dt     equal 0.003 # time step size in fs
variable Neq    equal 30000 # number of equilibration steps
variable Nque   equal 300000 # number of quenching steps -> determines quench rate
variable Teq    equal 1700 # equilibration temperature 
variable Tfin   equal 300 # quench to final temperature 
variable Nrep   equal 10 # number of unit cell repititions in each direction
# -> cubic box with side length 4.05 * Nrep / 10 nm 

# Set up basics
units           metal
atom_style      atomic
boundary        p p p

# Newton setting changes required communication distance 
newton		    on

# Define the initial lattice and geometry
lattice         fcc 4.05 # Al
region          box block 0 ${Nrep} 0 ${Nrep} 0 ${Nrep} 
create_box      1 box
create_atoms    1 box

mass            1 26.981539 # Al

# Define potentials
pair_style	    jaxnn cuda12 0.95
pair_coeff	    * * /home/weilong/workspace/chemsim-lammps/examples/aluminium/output/aluminum_MACE_r_cutoff_0.5_2025_3_21_all_test/model_default.ptb 1.1 1.1

# Set neighbor communication
neighbor 	    2.0 bin
neigh_modify	delay 0 every 1 check yes

# # Has to be r_cut * (mpl + 1) + skin_dist = 5*(4+1) + 2.5
# For Allegro #MLP = 0 ==> 5 * (2 + 1) + 2 = 7 
comm_modify     mode single cutoff 17

#-------------	Equilibration -------------#

# Minimize energy to prevent explosion in first step
minimize	    1.0e-5 1.0e-5 10000 100000
reset_timestep	0

# Record temperature data
variable        temp equal temp
fix             temp_log all print 100 "${temp}" file ./output/temp.txt screen no

# Setup thermodynamic and simulation parameters
timestep	    ${dt}
thermo		    100
thermo_style    custom step temp pe etotal press
thermo_modify   flush yes

# Output data for post-simulation analysis
dump            all_sim all atom 1000 ./output/dump.all  # Saves the entire simulation
dump            equil all atom 1000 ./output/dump.eq # For melting phase only

# Equilibrate at high temperature to melt the structure
velocity        all create ${Teq} 12345 mom yes rot yes dist gaussian
fix             1 all nvt temp ${Teq} ${Teq} 1.1

run             ${Neq}

#-------------	Solidification -------------#

# Prepare solidification phase
unfix           1
undump          equil

# Output only solidification data
dump            quench all atom 1000 ./output/dump.que # For quenching phase only
fix             2 all nvt temp ${Teq} ${Tfin} 0.1  # Quench to final temperature
run             ${Nque}

# Write final configuration data
write_data      ./output/data.run

# End of script
