# input script for simulation of 1ubq
dimension   3
units       metal
boundary    p p p
atom_style  atomic
neighbor        2.5 bin
neigh_modify    every 10 delay 0 check yes
# neigh_modify    one 100000
# neigh_modify    page 1000000
# Has to be r_cut * (2 * #MPL + 1) + skin_dist = 5 + 2.5
comm_modify     mode single cutoff 7.5
newton      on
read_data       water.lmp
mass        1 15.9994
mass        2 1.008
pair_style	    jaxnn cuda12 0.95
pair_coeff	    * * /home/weilong/workspace/chemsim-lammps/output/water_Allegro_r_cutoff_0.5_2025_2_27_new_atom_types/model_default.ptb 1.1 1.1

# 4) Visualization
thermo 10
thermo_style custom step temp pe ke etotal press
velocity    all create 300 23456789
fix         1 all nve
fix         2 all langevin 300.0 300.0 100. 1530917
timestep    0.0005
# Log data
thermo      1000
thermo_style    custom step pe ke etotal temp vol
dump        1 all custom 200 water.lammpstrj id type x y z
run         2000000