# input script for simulation of 1ubq
dimension   3
units       metal
boundary    p p p
atom_style  atomic
neighbor        2.5 bin
neigh_modify    every 10 delay 0 check yes
# neigh_modify    one 100000
# neigh_modify    page 1000000
# Has to be r_cut * (2 * #MPL + 1) + skin_dist = 5 + 2.5
comm_modify     mode single cutoff 8.5
newton      on
read_data       water.lmp
mass        1 15.9994
mass        2 1.008
pair_style	    jaxnn cuda12 0.95
pair_coeff	    * * /home/weilong/workspace/chemsim-lammps/examples/bulk_water/output/water_Allegro_r_cutoff_0.6_2025_3_10_emd_128_full_dataset/model_default.ptb 1.1 1.1

# energy minimization
minimize 1e-5 1e-7 1000 5000
# 4) Visualization
thermo 10
thermo_style custom step temp pe ke etotal press
velocity    all create 300 12345

fix 1 all npt temp 300.0 300.0 100. iso 0.98692 0.98692 1000.

timestep    0.0005
# Log data
thermo      1000
thermo_style    custom step pe ke etotal temp vol
dump        1 all custom 200 water_192atoms_npt.lammpstrj id type x y z
run         2000000